language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
install:
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
script:
  - dzil test --author --release
sudo: false
